backend:
  name: github
  repo: lancoha/Hydrargium
  branch: main
  auth_type: pkce
  app_id: Ov23lizkpzeHMpZts6nW
  api_root: https://api.github.com
  auth_endpoint: https://github.com/login/oauth/authorize

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date,  name: date,  widget: datetime }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Body,  name: body,  widget: markdown }
